# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: LibreTranslate"
  org.opencontainers.image.description: "Install LibreTranslate on your Home Assistant OS."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
